### ISSUE TITLE
Push 0.6.1 to Rubygems

### ISSUE THREAD

**Issue by wasabigeek** [zombocom/rack-timeout#175]
Hi maintainers, would appreciate the latest version being available on Rubygems 🙇

**Comment by TomA-R** [comment]
hey @kch / @schneems / @wuputah sorry for the direct ping but this would be really good and presumably fairly low effort - any chance you could push 0.6.1 to Rubygems? Thanks in advance

**Comment by carlwiedemann** [comment]
Friendly bump on this one.
