### ISSUE TITLE
possibility to timeout only for GET requests ?

### ISSUE THREAD

**Issue by loicginoux** [zombocom/rack-timeout#197]
Hello, 
I don't see the possibility to configure rack timeout to work only for GET requests. How difficult would it be to add a config to specify which http methods it can timeout (or the ones for which rack timeout is disabled) ?
We would like to drop GET requests in case of timeout but would want to not loose important POST/UPDATE/DELETE requests even if they take too much time.
Thanks

**Comment by wuputah** [comment]
There's been many requests and several PRs over the years to be able to do this or something similar. The general conclusion has been this is an anti-pattern. The most vigorous debate took place in #110, which I welcome you to review.

I think if we can find a _sustainable_ approach that allows people to customize the behavior, but does not endlessly add more options/option handling, then this might have a future. However, this might require significant refactoring.

In this case I am going to suggest merging any further discussion of this issue into #213. Thanks!
