### ISSUE TITLE
Excessive log output

### ISSUE THREAD

**Issue by barmstrong** [zombocom/rack-timeout#60]
After upgrading to rack-timeout 0.1.1 we get a bunch of log output like this in development when loading a single page:

https://gist.github.com/barmstrong/56481bcf7de9c29838fd

What does this output mean and any idea why so much of it?  Thanks!

**Comment by rafaelcgo** [comment]
:+1:

**Comment by coorasse** [comment]
+1 definitely annoying

**Comment by kch** [comment]
The funny thing with rack-timeout logging is that in development you hardly need to see any logs at all, and in production you'll want it somewhat verbose, at least when debugging issues.

I still think removing the logger in development is the best idea. Or even disabling rack-timeout entirely.

**Comment by jocko-wowza** [comment]
I agree that the fact that the default logging output is verbose and uninformative in a development state should be fixed.  Perhaps invert the logging, if the polling is working, just output a debug log message that polling is started, and then stop logging unless you come across an issue with the polling cycle.  That way we hear about the bad news, and not constantly about the good news.

**Comment by jocko-wowza** [comment]
I think it could be argued that it should only log if the state changes.   Being that its the `state change observer` that causing output.  If there is no state change, there is nothing to observe, and therefor nothing to log.

**Comment by wuputah** [comment]
The docs are now at [doc/logging.md](https://github.com/sharpstone/rack-timeout/blob/master/doc/logging.md).

Giving the verbosity of debug and info, error may indeed be a more reasonable default. You can set this explicitly:

```
Rack::Timeout::Logger.level  = Logger::ERROR
```

**Comment by jocko-wowza** [comment]
Thanks!

**Comment by wuputah** [comment]
I opened #146 to consider this further.
